global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30s
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'

#  webhook_configs:
#  - url: 'http://localhost:9093/api/v2/alerts'

  email_configs:
  - to: 'vladilen.marchenko@gmail.com'
    from: 'vladilen.marchenko@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'vladilen.marchenko@gmail.com'
    auth_identity: 'vladilen.marchenko@gmail.com'
    auth_password: 'password'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance' ]
